[project]
name = "ai-engineer-journey"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "rathnavel24", email = "121199806+rathnavel24@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "google-genai>=2.24.0",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
]

[tool.uv]
package = false

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.8",
]
